# Setup the environment.
# This is where you configure your build envionment. For Drupal, we're using a PHP 8.4
# environment with the latest MySQL 8.0 database. Other database options are provided
# such as mariadb, postgresql, and mysql 5.7, 8.0 and 8.4. PHP versions are available
# from PHP 5.6 - PHP 8.5. Make sure you select the version of PHP most appropriate for
# the version of Drupal you are using. You can also use other versions for the purposes
# of testing in other versions.=
type: lamp
php: 8.4
database: mysql:8.0

# These are our build steps. Because we're starting with a fresh install, we need to install
# Drupal 11 with composer. If you have an existing composer.lock file, you can skip the steps
# to install the base project and simply use `composer install` at this step.
steps:
  - name: Install The Latest Modern Drupal With Composer
    plugin: Script
    script: |
      cd $SRC_DIR/web
      composer create-project drupal/recommended-project ./web
      composer require drupal/admin_menu
      composer require drupal/devel
      composer require drush/drush

  # We need to tell Probo.CI that we're using a Drupal site so the database is properly configured
  # and settings.php files are also properly configured.
  - name: Set Up The Drupal Plugin To Inform Probo.CI we'ree using a Drupal web site.
    plugin: Drupal
    drupalVersion: 11
    clearCaches: false
    databaseUpdates: false
    subDirectory: web/web

  # This will install a demonstration Drupal site with a standard username and password. Note that the
  # database username and password does not need to be changed and is a non-privileged user. The password
  # assigned can be configured and is not really a secret given it is insulated by using Docker contaienrs
  # to run as opposed to being accesible outside the application.
  - name: Run Drupal Installation using drush
    plugin: Script
    script: |
      cd $SRC_DIR/web
      drush site-install -y --account-name=admin --account-pass=admin --db-url=mysql://probo:strongpassword@localhost:3306/drupal --site-name="Modern Drupal Probo.CI Example" --site-mail="admin@example.com" --locale=en --langcode=en --yes  
      drush en admin_menu devel -y    
      drush cr

  # This step is optional given we are assigning our username and password in the previous step, but you can
  # leverage this technique to quickly log in to your Probo.CI environment with your privileged account.
  - name: Get Drush uli For Our site
    plugin: Script
    script: |
      cd $SRC_DIR/web
      drush uli

