<?php

// function nel_preprocess_block(&$variables) {

//   // Pass the block and region name as attributes into the block's content
//   if (isset($variables["elements"]["#id"])) {
//     $block_id = $variables["elements"]["#id"];
//     $block = \Drupal\block\Entity\Block::load($block_id);

//     if ($block) {
//         $variables["content"]["#attributes"]["region"] = $block->getRegion();
//         $variables["content"]["#attributes"]["block"] = $block->id();
//     }
//   }

// }
